
[build]
  command = "git submodule update --init --recursive && npm install && npm run build"
  publish = "dist"

[context.production.environment]
  NETLIFY_USE_YARN_CACHE = "true"

  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  


